# Generated by Django 2.2.5 on 2019-09-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('rate_per_btc', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
